[workspace]
members = [
  "vote",
  "vote/meta",
  "buy_serum",
  "buy_serum/meta",
  "token_staking",
  "token_staking/meta",
  "nft_staking",
  "nft_staking/meta",
  "multiple_nft_staking",
  "multiple_nft_staking/meta",
  "swap_esdt",
  "swap_esdt/meta"
]
