[package]
name = "swap_esdt-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.swap_esdt]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.34.1"
